### PR TITLE
add a show method to raster type

### PR DESCRIPTION
**Pull request by marciolegal**
Finally?

### CODE REVIEW

**Comment by visr** [comment]
Thanks for the perseverance. I gave it a quick spin and it seems ok:

``` julia
julia> include("runtests.jl")

julia> A
RasterIO.Raster (Driver: GTiff/GeoTIFF)
Image Structure: --INTERLEAVE=BAND
File(s): data/A.tif
Dataset (width x height): 3 x 3 (pixels)
  Band 1 (Gray): 3 x 3 (Int32)
Number of bands: 1

julia> A2
Closed Raster Dataset
```

**Comment by yeesian** [comment]
LGTM :clap:

**Comment by marciolegal** [comment]
Thanks for the patience. That was a good git exercise -- now can start start working on the contributions promissed. I can come back to the raster object later for the list of properties, but for now I want to work with reprojections. When working with raster datasets, many times you use original raster data in different projections, so it would be a good idea to already provide some reprojection functionality.

I have made a rudimentary function to do that before starting working with thisfork and it worked well. I will bring it here for discussion, after rewriting it using our gdal functions. However, my implementation used OGR binding, which we still dont have. Could these be provided?

**Comment by meggart** [comment]
Does this help in any way? https://github.com/meggart/OGR_Wrapper It is just a raw wrapper of ogr_api.h Let me know if you need something else.

**Comment by marciolegal** [comment]
Yes. Thank you Fabian.

**Comment by yeesian** [comment]
You might want to have a look at https://github.com/visr/GDAL.jl now too

**Pull request merged**
