### PR TITLE
julia 0.4 is already out

### PR DESCRIPTION
**Pull request by yeesian**

### CODE REVIEW

**Comment by yeesian** [comment]
@visr @meggart is TravisCI supposed to be green here? Should we bump `julia 0.4-` to `julia 0.4` before tagging?

**Comment by meggart** [comment]
Yes, we probably should. I don't know how many prerelease installations are still around, is there any disadvantage from keeping 0.4- for a while?

**Comment by meggart** [comment]
Regarding the Travis error, it looks like there is some precompilation error when building Conda and BinDeps. I have seen this error locally on my machine before when trying to get the NetCDF dependencies by Conda...

**Comment by yeesian** [comment]
It could be that Travis needs to update their cache? I managed to build this package fine on master on OS X with the changes from #11. Not sure about Linux

**Comment by yeesian** [comment]
> is there any disadvantage from keeping 0.4- for a while?

Nothing in particular, but we'll be asking ourselves that everytime we decide whether or not to bump the REQUIRE file. Supporting only the stable release of the language (when it's available) sounds like a sensible level of volunteer support to provide.

**Comment by yeesian** [comment]
I forgot this package isn't even in METADATA yet.

**Pull request merged**
