### PR TITLE
Major re-organization

### PR DESCRIPTION
**Pull request by yeesian**
~~Warning: Not ready for merge.~~

~~More to come. I'll type up a brief description of the changes to expect.~~
# Code Organization

We should separate the lower-level GDAL-facing routines from the higher-level RasterIO ones.
## lower-level

In the lower-level GDAL-facing routines, we have `src/gdal_api.jl` to import from the following folders:
- `src/clang/*.jl` -- generated by Clang (with manual edits [to make it work] in the `capi` branch)
- `src/gdal/*.jl` -- hand-written, mostly corresponding to functions in `src/clang/gdal_cfuns.jl`, but with error-checking, and docstrings (to be added); this will be the file that developers refer to and modify (instead of `src/clang/gdal_cfuns.jl`) when developing code for the higher-level routines (in the next section).

This is the layer where
- pointer arithmetic should be handled
- error messages should be dealt with
- C-type immutables/structs (for the express purpose of interfacing with the GDAL library, rather than for users) should be defined, and dealt with locally

We should not be defining our own RasterIO types here, unless it's needed (for the sole purpose of interfacing with libgdal).
## higher-level

The higher-level user-facing routines are organized into `src/raster_types.jl` and `src/raster_functions.jl`.

This being a wrapper library, I'm biased towards maintaining handles/pointers to the corresponding gdal/raster objects, rather than providing our own types (unless we have a compelling replacement of alternative functionality for our own types).

### CODE REVIEW

**Comment by yeesian** [comment]
RFC: @timholy @marciolegal @c42f @wkearn @meggart @visr @garborg

I think I'm slowly getting around to the core decisions for this package, pertaining to "Raster I/O", and "In-Memory Representation"

# Raster I/O

There are two types of I/O we're trying to perform, which I'll describe as
- "gulping" -- where you read in the data all at once into memory
- "sipping" -- where you're maintaining a handle to the underlying data, and work with it through windowed buffers, individual bands, etc

(From the way things are progressing [in this PR], we'll almost surely be providing the methods for "sipping" first; and might later come back to provide methods for "gulping")

## Gulping

I believe @wkearn's original intention (which is the current master) was to "gulp" the entire dataset into memory, before working with it. Although it is what most of us would want, this is a "special case" of "sipping" (described in the next sub-section)

## Sipping

Is one of the organizing principles of https://github.com/mapbox/rasterio, and brought up in @marciolegal's suggestion in https://github.com/wkearn/RasterIO.jl/issues/6.

The idea is to view rasters as "datasets", consisting of "blocks"/windows of "bands"/channels, and to open/close handles to them, and [working on them in a windowed/block-wise fashion](https://github.com/mapbox/rasterio/blob/master/docs/windowed-rw.rst), akin to how we would process files (`readlines` versus `readline`).

# In-memory representation

Regardless of the I/O method (in the previous section), we also have to deal with how the data should be represented in memory (mapbox/rasterio works with numpy.ndarrays).

I'll start with vanilla arrays here (in this PR), and we can review the decision down the road. But I'm in favour of decoupling the "data/handles" from the "geospatial projections/transformations", rather than combining them together into a custom "geo-referenced `Array{Bands,N}`" replete with bells and whistles.

## Dataset Handles should behave like handles, not Arrays

I am _not_ in favour of the following proposal in  https://github.com/wkearn/RasterIO.jl/issues/6#issue-104601554

> A good thing to do would be to implement a funtion that allows to directly retrieve data from disk using a syntax like myraster[1:I, 1:J].

Instead, we will provide the methods for them to "sip" the data into julia's arrays, and let them handle it from there, rather than giving them the false impression of it being Array-like in performance.

## Working more closely with `Images.jl`

I'm open to changing my mind but, from what I see (i.e. [RasterIO::DataModel](https://github.com/wkearn/RasterIO.jl/blob/major-refactor/src/DataModel.md)), the data here is not so different from [those in Images.jl](https://github.com/timholy/Images.jl/blob/master/doc/core.md) that we should be defining our own types (and providing our own getindex methods).

## Working more closely with `Proj4.jl` (or the currently non-existent `OGR.jl`)

For working with the geotransform/coordinate-system attributes of the raster.

**Comment by timholy** [comment]
Seems interesting. Definitely interested in joining forces with regards to Images.

I don't know anything about your files/datasets, how big are they? I'm guessing you can't just `mmap` as a big array because there's some kind of encoding/compression?

**Comment by yeesian** [comment]
> I don't know anything about your files/datasets, how big are they?

I haven't dealt with rasters in my personal work (this was mostly to set the foundational work for @marciolegal and other interested developers) so I can't really say... a few kB to a few GB? :sweat_smile:

Here's a list of the file formats (that GDAL has drivers for): http://www.gdal.org/formats_list.html

> I'm guessing you can't just mmap as a big array because there's some kind of encoding/compression?

I'm guessing that's what most people will want to do (and they probably should be using Images.jl in those cases); But yes, people might use GDAL/RasterIO to deal with file formats that might be composed of multiple (irregular) [blocks of data](https://github.com/wkearn/RasterIO.jl/blob/major-refactor/src/DataModel.md#raster-band), each with their own shape. (Well-bred files have identically blocked bands, but GDAL allows otherwise).

**Comment by visr** [comment]
In my case most files will fit into RAM, however with new high resolution datasets this is becoming less often the case. Large datasets are generally tiled into rasters of max a few GB, but naturally this is also more of a hassle to deal with. (Hence the popularity of things like Google's Earth Engine which hides all this complexity in the cloud.)

Directly `mmap`ping the files will not be possible in general indeed because of encoding and compression. I also just came across this, however it seems to be Linux only: https://trac.osgeo.org/gdal/wiki/rfc45_virtualmem

**Comment by marciolegal** [comment]
HI all
This looks good. Unfortunately I will be rather busy till Wednesday, then can help more.
Yes, there are all kinda of compressions depending on the format, all the way to formats where the user itself can control it (e.g: Netcdf). Considering the different data formats, my idea was to just define the raster type as to have a handling to the gdaldataseth, and then wrap gdal functions to do the operations we want, as a way to advance more quickly. But if we can do that in more elaborate ways, then it is great!

Individual images can be as big as several hundreds of megabytes. However in many cases you have to work with mosaics of several images of this size, easily resulting in several GB big datasets. Geoprocessing operations are then performed on the entire mosaic.

**Comment by c42f** [comment]
For better or worse, we have an entirely custom image processing pipeline at work, so I don't have enough experience with the GDAL API to make much in the way of useful recommendations.  The datasets we have are "arbitrarily large" compared to the memory available on a single machine, so are processed piece by piece across a cluster.

I'm definitely happy to get any bits and pieces into Proj4.jl which would help with interoperability here.

**Comment by meggart** [comment]
Thanks for the initiative, @yeesian 

when you describe the different approaches of _gulping_ and _sipping_ I use both of them in my day-to-day work and I think both of them deserve a special high-level interface. I think it would be great if we could make a single function that just reads an entire dataset which fits into memory and returns a subtype of `AbstractImage` (GeoImage ??), so that one can immediately use many of the great tools available in Images.jl  Such an interface would be great for users who just want to quickly load a dataset and work on it and don't want to think about layered access to the data or destructing Dataset Handles. I would ilke to work on such a function, once this is merged. 

The other interface where the data is not read immediately but represented by a handle is then the other part. I am quite neutral on if the handle should be an `AbstractArray` and things like `x[i,j,k]` should be possible, as @marciolegal described, both would be ok for me.

**Comment by yeesian** [comment]
> I think it would be great if we could make a single function that just reads an entire dataset which fits into memory and returns a subtype of AbstractImage (GeoImage ??), so that one can immediately use many of the great tools available in Images.jl

Although it won't be done in this PR, I'm on board with an `imread()`-like function too! Alternatively, you might want to implement GDAL as a [driver for Images.jl](https://github.com/timholy/Images.jl/blob/master/doc/extendingIO.md).

> I am quite neutral on if the handle should be an AbstractArray and things like x[i,j,k] should be possible, as marcio described, both would be ok for me.

FWIW, as Martijn has pointed out, parts of it is already in GDAL (albeit only for Linux) through the methods:

``` julia
GDALDatasetGetVirtualMem
GDALRasterBandGetVirtualMem
GDALGetVirtualMemAuto
GDALDatasetGetTiledVirtualMem
GDALRasterBandGetTiledVirtualMem
```

The current model of working through `GDAL::RasterIO()` is not a good way for indexing into individual pixels (even though it's possible), and we haven't yet laid the groundwork for supporting those `getindex` methods (even if we did, it still won't be as performant as working in a windowed/block-wise fashion).

**Comment by marciolegal** [comment]
Implementation to allow for a workflow like the following would conform with most of what was discussed so far (at least I'd love to be able to work like that).

myraster = Raster(filename; inMem=true)

Could get the whole thing into memory while

Raster(filename, inMem=false)

Would return the handle.
Then getindex could be used in all cases:
For example, data=Raster(R1, R2, R3) where Rs are ranges could be arranged depending on inMem to call the appropriate getindex method. When inMen=true, windowed/block sipping would activate, including stride parameters. If we are not happy with  individual indexing when inMem=true, could just throw an exception if they are used.

Maybe then data could be converted to use images.jl functions (sorry, don't know that package).

Writing to disk could be done in similar way with setindex. This all implies Raster being a subtype of AbstractArrays.

**Comment by yeesian** [comment]
@marciolegal I'm going to be busy for the next few days. The stuff in `src/gdal/*` should be pretty comprehensive by now, so if you want to have a look, feel free to check them out. It's also a good time for me to step back, review the code and have a look at what other similar projects do.

**Comment by marciolegal** [comment]
@yeesian Looks great! By the looks of if you basically nailed the raster part. Can't wait to test it with my data.
A note: on windows, I am geting an error in gdal_cdefs.jl: type could not be constructed. This happens in all lines similar to "const GDT_Byte = (UInt32)(1)". Using type functions work.

**Comment by yeesian** [comment]
> A note: on windows, I am geting an error in gdal_cdefs.jl: type could not be constructed. This happens in all lines similar to "const GDT_Byte = (UInt32)(1)". Using type functions work.

I haven't touched the `gdal_cdefs.jl` file much. Which version of julia are you on? I'm working on the basis we're only going to support julia v0.4

**Comment by marciolegal** [comment]
@yeesian 
Yes, I'm using 0.3 as 0.4 never worked for me with Juno, neither downloading binaries or compiling from source. You can disconsider the bug or maybe can be used to warn people in 0.3.

Some more issues related or not with Julia 0.3.
- Cint(number) doesnt work.
- The systax  bellow didn't work:

```
function GDALDataTypeIsComplex(arg1::GDALDataType)
    ccall((:GDALDataTypeIsComplex,libgdal),Cint,(GDALDataType,),arg1)
end
```

libgdal needs to be "libgdal", and on Windows, requires the name of the registered gdal dll. In my case it was "gdal201".

**Comment by yeesian** [comment]
@marciolegal, maybe you can do a separate PR (after this one gets merged) to provide support for v0.3*? I'm not sure it'll be worth the effort though, given that this package wasn't ready for public consumption, and [v0.4 will be out really soon](https://groups.google.com/d/msg/julia-dev/AHjZcyd_MsU/w_9zc1xEAQAJ).

*I have already moved on to [working with GDAL 2.0](https://github.com/wkearn/RasterIO.jl/pull/7#issuecomment-137981863), and think that the effort spent supporting v0.3 might be better spent working on conditional loading for people using different versions of GDAL.

**Comment by meggart** [comment]
I agree that this package should only support v0.4, especially if we want to try any AbstractArray magic. Regarding support of different versions of GDAL, I think it would make much more sense to get the deps branch working and then just install GDAL 2.0 by default. 
I recently did some test for Mac, which worked smoothly since https://github.com/JuliaLang/Homebrew.jl/issues/44 is done. (However, this will install GDALL 1.11.)

Maybe we can just create a PR on the deps branch to have this as an open issue.

**Comment by yeesian** [comment]
Sorry for the delay -- this branch/PR is now ready for review.

This notebook is the best example of some fo the supported operations as of now: https://github.com/wkearn/RasterIO.jl/blob/major-refactor/doc/RasterioGuide.ipynb

@marciolegal, did you manage to get a working copy of julia0.4-RC yet?

**Comment by visr** [comment]
To get the tests to pass locally on my Windows laptop with 0.4-RC, I have to add

``` julia
RasterIO.closeraster(A2)
```

before removing the files at the end, otherwise `rm` cannot remove them. Adding this makes the tests pass, though I do get

```
julia> Pkg.test("RasterIO")
INFO: Testing RasterIO
ERROR 10: Pointer 'hDS' is NULL in 'GDALClose'.

INFO: RasterIO tests passed
```

**Comment by yeesian** [comment]
Thanks @visr, I appreciate it! Do you know how documentation should work with multi-dispatch?

**Comment by visr** [comment]
The doc system just shows multiple entries. So I guess the first, most general entry can get a full doc entry, with some extra lines added for the more specialized entries?

``` julia
julia> @doc "f for Integer" ->        
       f(x::Integer) = x + 1          
f (generic function with 1 method)    

julia> @doc "f for Int16" ->          
       f(x::Int16) = x + 2            
f (generic function with 2 methods)   

help?> f                              
search: f fd for fma fld fft full find

  f for Integer                       

  f for Int16                         
```

**Comment by yeesian** [comment]
Ah, I see. Shall documentation/tests/etc (for the RasterIO functions/types) go into another PR?

**Comment by visr** [comment]
Yeah no need to put everything in this one PR, it's already pretty much a rewrite. New solid base to build upon.

**Comment by yeesian** [comment]
Can I get everyone with a working interest in this package to checkout this PR, and give their inputs by this friday?

See if opening (importing/using) it in 0.4-RC works, and run `Pkg.test("RasterIO")`, before trying out the examples in https://github.com/wkearn/RasterIO.jl/blob/major-refactor/doc/RasterioGuide.ipynb

If there's no major dissent, I'll merge it on friday, and work on the documentation/tests over the weekend.

**Comment by marciolegal** [comment]
I'm totally caged this whole week, I'll do what I can before Friday.

---

De: Yeesian Ngmailto:notifications@github.com
Enviada em: ‎14/‎09/‎2015 20:34
Para: wkearn/RasterIO.jlmailto:RasterIO.jl@noreply.github.com
Cc: marciolegalmailto:marciolegal@hotmail.com
Assunto: Re: [RasterIO.jl] Major re-organization (#8)

Can I get everyone with a working interest in this package to checkout this PR, and give their inputs by this friday?

See if opening (importing/using) it in 0.4-RC works, and run `Pkg.test("RasterIO")`, before trying out the examples in https://github.com/wkearn/RasterIO.jl/blob/major-refactor/doc/RasterioGuide.ipynb

If there's no major dissent, I'll merge it on friday, and start on the documentation/tests shortly after.

---

**Comment by meggart** [comment]
I had some time to play with this today, this already looks awesome. 

The only thing where I stumbled on a fresh julia install was a missing Compat package, we should add this to REQUIRE. From my side you can merge this whenever you want.

**Comment by garborg** [comment]
Working well for and looking good to me, too.

**Comment by yeesian** [comment]
> The only thing where I stumbled on a fresh julia install was a missing Compat package, we should add this to REQUIRE.

We don't seem to require it though, so I've removed it from `clang/gdal_cdefs.jl` (the only occurrence).

**Comment by visr** [comment]
Two last things. In your notebook the image of the island appears transposed when you create it from the array, but it is correct if `imread()` reads it. Perhaps you should consider adding the spatial order when constructing the `Image`:

``` julia
Images.Image(o, spatialorder=["x", "y"])
```

Though this can be addressed later as well.

The other point is that it feels a bit strange to have to create `Cint`s for indexing into the array with functions like `fetch`. Can we not let ccall handle this?

**Comment by yeesian** [comment]
> Perhaps you should consider adding the spatial order when constructing the Image:
> 
> ```
> Images.Image(o, spatialorder=["x", "y"])
> ```

Oo, I didn't know about the `spatialorder` keyword, and agree that it should be used. We haven't provided routines for conversions to `Image`-types. It'll be great to have ppl chip in on that bit.

> The other point is that it feels a bit strange to have to create `Cint`s for indexing into the array with functions like `fetch`. Can we not let ccall handle this?

I agree with your points, and was hoping someone would point that out (:
1. I don't know if the ccalls will magically take in `Int64`s, and convert them to `Cint`s (and actually find it mentally easier to not assume so)
2. There is alot of intermediate code that returns/takes in `Cint` (e.g. `getxsize`), and I didn't want to translate back-and-forth between `Cint` and `Int64` unnecessarily (it can difficult to draw the line)
3. Nonetheless, I do think we should provide RasterIO functions that takes in and emits `Int`s, that does all of these conversions for the end-user
4. It's the same thing with the drivers, projections and geotransforms (whether to keep the respective pointers or the string/array). I dodged the issue by not having it in the `Raster` type (and because we'll have to do the housekeeping of making sure they're the same as the underlying dataset if we maintain our own copies).

**Comment by visr** [comment]
Yeah I agree it's hard to draw the line, but perhaps all user-facing code should be able to handle `Int`. Again, can also be done later. Regarding point one, yes it does, I took an example from RasterIO itself:

``` julia
julia> RasterIO.GDALGetDriver(Cint(3))
Ptr{Void} @0x0000000000252d60

julia> RasterIO.GDALGetDriver(3)
ERROR: MethodError: `GDALGetDriver` has no method matching GDALGetDriver(::Int64)

julia> ccall((:GDALGetDriver,libgdal),RasterIO.GDALDriverH,(Cint,),Cint(3))
Ptr{Void} @0x0000000000252d60

julia> ccall((:GDALGetDriver,libgdal),RasterIO.GDALDriverH,(Cint,),3)
Ptr{Void} @0x0000000000252d60
```

**Comment by yeesian** [comment]
But wouldn't the corresponding `_getdriver()` be type-unstable then?

**Comment by visr** [comment]
Why would that be, the return type does not change right?

**Comment by yeesian** [comment]
Hm yeah, I was probably too strict with the typing. Do you want to give it a shot (loosening the function signatures) in a separate PR? We've reached consensus pretty quickly, and can probably merge this PR by now.

**Comment by visr** [comment]
Sure, go for it, thanks for this :+1:

**Comment by yeesian** [comment]
Have at it (:

**Comment by c42f** [comment]
@yeesian `ccall` has quite a bit of conversion machinery to make things work smoothly without the need to annotate the types (I remember discussing this in Proj4.jl as well.)  Generally speaking it shouldn't be necessary to explicitly annotate any types unless you want to actually dispatch on them.

I suggest reading the relevant parts of the ccall docs:
http://julia.readthedocs.org/en/latest/manual/calling-c-and-fortran-code/#auto-conversion

**Comment by yeesian** [comment]
I do recall that conversation, and my concern has slowly drifted away from type-instability to comprehensibility: `Any` sounds too arbitrary/ambiguous. I'd rather identify a strict subset of allowable types that are guaranteed to work, rather than an arbitrary superset of types that aren't [guaranteed to work]. WRT @visr's examples:

``` julia
julia> ccall((:GDALGetDriver,:libgdal),RasterIO.GDALDriverH,(Cint,),3.0)
Ptr{Void} @0x00007fc1e5050820
```

works too, although I'm not sure I'd want it to.

@visr, `Integer` should probably be sufficiently permissive here. Can you give it a shot in your PR? If not, I'll get around to it this weekend

**Comment by c42f** [comment]
The other difference between annotating and not annotating is in the type of error you get: is an `InexactError` better or worse for a user than a `MethodError`?  Consider:

``` julia
julia> foo(a::Integer) = convert(Int, a)
foo (generic function with 1 method)

julia> bar(a) = convert(Int,a)
bar (generic function with 1 method)

julia> bar(3.0)
3

julia> bar(3.5)
ERROR: InexactError()
 in bar at none:1

julia> foo(3.0)
ERROR: MethodError: `foo` has no method matching foo(::Float64)
 in eval_user_input at REPL.jl:64
 [inlined code] from REPL.jl:93
 in anonymous at task.jl:68

julia> foo(3.5)
ERROR: MethodError: `foo` has no method matching foo(::Float64)
 in eval_user_input at REPL.jl:64
 [inlined code] from REPL.jl:93
 in anonymous at task.jl:68
```

Parameterizing the low level APIs with the _semantically_ correct abstract type (`Integer` in the case of `GDALGetDriver`) probably makes the most sense.  In that case, you correctly get an `InexactError` if an input of type `T <: Integer` can't be converted to a `CInt`; nonsensical inputs like floats produce a `MethodError`.

**Comment by mkborregaard** [comment]
Hi, I hope it is OK I comment on this thread - I am a (coming) end-user of the Geo package, and really looking forward to the functionality you guys are working so hard for :-)

I have a question that may be of relevance to how the data structure is represented, and that is that of plotting the rasters. The Image format is geared towards plotting (and editing) images. For Rasters, on the other hand, one of the central uses is to be plotted together with vector shapefiles, text, and point data. My feeling is that the best way of doing that might be to let the Compose.jl package handle the plotting, and defining raster grid cells as rectangles in these vector plots. This, I think, is very different from how the Images package handles images, which could be an argument against using the Images data format for rasters.
Does this make sense to you?

**Comment by visr** [comment]
Since rasters and images are very similar, I believe it makes sense to integrate rasters with Images.jl. It is true that it would be nice to plot rasters and vectors together, though we're not that far yet. Your suggestion for drawing pixels as squares in Compose sounds like it would suffer from bad performance, however there is ongoing work on being able to embed bitmaps into Compose, see https://github.com/dcjones/Compose.jl/pull/141
So I believe it's not a choice of either Images or Compose, but both could be made possible.

**Comment by mkborregaard** [comment]
I do see the point that they are similar. I will say that I am highly in favour of thinking the end use scenario into the design at the outset - so it would be cool if rasters, shapefile polygons and points could be plotted together, preferably with on-the-fly reprojections to the plot window projection frame so data can be reliably placed atop each other (which was the reason I thought individual polygons rather than an image would be a good idea). If that is possible with the work being done in compose, that would be awesome. Thanks for responding!

**Comment by marciolegal** [comment]
Finally had time to do some tests and it works. Very nice job from @yeesian. Congrats. Specially like all the fetch methods.
I agree with mkborregaard on plotting concerns. To be competitive with GIS solutions of similar software (Matlab's Mapping toolbox and R's Raster/OGR packages), it will need at least the capability of ploting layers of raster/polygon data, with on-the-fly reprojections. If possible, including some annotation such as scale bars, feature labels and north arrows. This could be very challenging, but will be eventually needed for successful implementation of GIS in Julia (meaning, being able to do some basic GIS analysis without the need of extra software).

**Comment by yeesian** [comment]
> I have a question that may be of relevance to how the data structure is represented, and that is that of plotting the rasters. The Image format is geared towards plotting (and editing) images. For Rasters, on the other hand, one of the central uses is to be plotted together with vector shapefiles, text, and point data. My feeling is that the best way of doing that might be to let the Compose.jl package handle the plotting, and defining raster grid cells as rectangles in these vector plots. This, I think, is very different from how the Images package handles images, which could be an argument against using the Images data format for rasters.
> Does this make sense to you?

RasterIO.jl currently take in (and emit) raw arrays of values (usually `Uint8`s). Whether or not you pass it on to Compose.jl or do a roundtrip through Images.jl is still up to you.

How does the discussion on plotting vector geometries come into the picture? There might be plans to ["rasterize" vector geometries](https://github.com/mapbox/rasterio/blob/master/docs/features.rst) in this package in the future (PRs welcome), but it is not an immediate priority to me.

From what I know, the JuliaGeo-suite of packages does not have any ambition of providing her own plotting library, but we'll try to make it easier for users to work with existing plotting libraries in julia.

**Comment by yeesian** [comment]
> I will say that I am highly in favour of thinking the end use scenario into the design at the outset - so it would be cool if rasters, shapefile polygons and points could be plotted together, preferably with on-the-fly reprojections to the plot window projection frame

We can do with some help (:

PRs for [warping/reprojections of rasters](https://github.com/mapbox/rasterio/blob/master/docs/reproject.rst) will be very welcome.

**Comment by mkborregaard** [comment]
Sorry if this is a stupid question, I do not have an appreciation of the details here - but does gdal not handle such transforms?

**Comment by yeesian** [comment]
Which transforms? GDAL can do warping/reprojections, but we haven't yet made it easy to do so in this package. But it sounds like something @marciolegal might [get around to](https://github.com/wkearn/RasterIO.jl/issues/6#issue-104601554).

**Comment by mkborregaard** [comment]
fantastic :-)

**Pull request merged**
