### PR TITLE
Fixed 0.5 deprecations

### PR DESCRIPTION
**Pull request by mauro3**
Fixed 0.5 deprecations ~(without any thoughts beyond search and replace)~.

### CODE REVIEW

**Comment by mauro3** [comment]
Also updated the .travis.yml file.

**Comment by mauro3** [comment]
Updated by removing unnecessary `@compat` annotations.

**Comment by mauro3** [comment]
Bump.  Any chance of a review/merge?

**Comment by yeesian** [comment]
Thanks! And sorry for the slow response!

**Comment by mauro3** [comment]
No worries and thanks!

**Pull request merged**
