### PR TITLE
Update C API

### PR DESCRIPTION
**Pull request by yeesian**
for gdal v1.11.2.

based on the latest changes in https://github.com/meggart/GDALfuns.jl/commit/94636eb6ef93bf11ea824a9fe5908b8e6dd724e0

~~@meggart, the following files also need to be clang'ed: http://www.gdal.org/cpl__minixml_8h_source.html and http://www.gdal.org/cpl__quad__tree_8h_source.html~~
(Edit: I'm just going to set the corresponding CPL\* types to `Void` for now, and hope it works)

According to the manual,

> However, C functions that generate and use opaque struct types by passing pointers to them can return such values to Julia as Ptr{Void}, which can then be passed to other C functions as Ptr{Void}.

### CODE REVIEW

**Comment by yeesian** [comment]
tests passing on julia v0.4. I'm not motivated to provide/maintain support for v0.3, given that this package hasn't been released yet.

@meggart @wkearn, ready for any of your review

**Comment by visr** [comment]
Thanks for this! Is there a reason to stick with GDAL 1.11.2, and not directly switch to 2.0.0, released in June?

**Comment by yeesian** [comment]
> If we only support Julia 0.4 and later, I think this can go? Otherwise it probably needs to be added to a REQUIRE file. The REQUIRE file should then also have julia 0.4-

Having `julia 0.4-` in REQUIRE means that we're only willing to support up to julia 0.4; see [Creating a new Package](http://julia.readthedocs.org/en/latest/manual/packages/#require-speaks-for-itself):

```
"You might also have no interest in supporting the development version of Julia. Just as you can add a floor to the version you expect your users to be on, you can set an upper bound. In this case, you would put julia 0.x 0.y- in your REQUIRE file. The - at the end of the version number means pre-release versions of that specific version from the very first commit. By setting it as the ceiling, you mean the code supports everything up to but not including the ceiling version."
```

 which is probably not what we want. Instead, we'll have `julia 0.4` in REQUIRE, and wait til julia 0.4 is actually released before registering this in METADATA, which is fine, since this package has quite some work left before it's ready for release anyway

> Is there a reason to stick with GDAL 1.11.2, and not directly switch to 2.0.0, released in June?

None, except that it is the version of GDAL that Fabian has used Clang to generate the wrapper for. Doesn't mean that we can't support GDAL 2.x (if the API hasn't changed by then)

**Comment by visr** [comment]
Maybe you can help me understand, but now that Clang.jl generated proper Julia functions such as  `GDALOpen(pszFilename::Ptr{Uint8},eAccess::GDALAccess)`, this means we actually need to send it a pointer, whereas if `ccall` is used directly you can just call `GDALOpen` with a string as the first argument, not a `Ptr{Uint8}` as is needed now. Do you think we should loosen certain signatures?

**Comment by yeesian** [comment]
> Do you think we should loosen certain signatures?

Yup, I'm doing a major refactor of the package. ~~Should I branch off this PR? Or branch off master?~~ I think I'll branch off this PR, and if I like what I see, I'll open a PR from that branch.

Edit: see PR #8

**Comment by visr** [comment]
Sounds good, thanks for your answers

**Comment by garborg** [comment]
> Having julia 0.4- in REQUIRE means that we're only willing to support up to julia 0.4

That would be true if it was listed as the closing number rather than the opening number in the require (e.g. `julia 0.3 0.4-`), but not for the opening number. E.g. `julia 0.4-` means supporting 0.4-pre, -rc, etc., as well as the release, and on to infinity. Some packages just switched their metadata reqs from `julia 0.3-` to `julia 0.3` now, long after 0.3 was in use.

**Comment by yeesian** [comment]
Ah I didn't know that, thanks for the clarification! That'll be helpful for Proj4.jl's REQUIRE file too

**Comment by garborg** [comment]
Good. Great seeing this package taking shape, by the way.

**Pull request closed without merging**
